//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopSolution.WebApp.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewLocalizationResource_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLocalizationResource_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("eShopSolution.WebApp.LocalizationResources.ViewLocalizationResource.en", typeof(ViewLocalizationResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add_to {
            get {
                return ResourceManager.GetString("Add to", resourceCulture);
            }
        }
        
        internal static string available_products {
            get {
                return ResourceManager.GetString("available products", resourceCulture);
            }
        }
        
        internal static string categoryUrl {
            get {
                return ResourceManager.GetString("categoryUrl", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Featured_Products {
            get {
                return ResourceManager.GetString("Featured Products", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Latest_Products {
            get {
                return ResourceManager.GetString("Latest Products", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string More_Details {
            get {
                return ResourceManager.GetString("More Details", resourceCulture);
            }
        }
        
        internal static string New___Available {
            get {
                return ResourceManager.GetString("New | Available", resourceCulture);
            }
        }
        
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        internal static string Product_Details {
            get {
                return ResourceManager.GetString("Product Details", resourceCulture);
            }
        }
        
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        internal static string productUrl {
            get {
                return ResourceManager.GetString("productUrl", resourceCulture);
            }
        }
        
        internal static string Related_Products {
            get {
                return ResourceManager.GetString("Related Products", resourceCulture);
            }
        }
        
        internal static string Sort_By {
            get {
                return ResourceManager.GetString("Sort By", resourceCulture);
            }
        }
        
        internal static string Specials_Offer {
            get {
                return ResourceManager.GetString("Specials Offer", resourceCulture);
            }
        }
        
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        internal static string View_details {
            get {
                return ResourceManager.GetString("View details", resourceCulture);
            }
        }
    }
}
